//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mongoose.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Application
    {
        public int ApplicationId { get; set; }
        public string Resume { get; set; }
        public int InternshipId { get; set; }
        public int StudentId { get; set; }
        [Display(Name = "Application Date")]
        [DataType(DataType.Date)]
        public System.DateTime ApplicationDate { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Internship Internship { get; set; }
    }
}
