//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mongoose.Models
{
    using System;
    
    public enum payMe : int
    {
        Payed = 0,
        NotPayed = 1
    }
}
