//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mongoose.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    public enum payMe : int
    {
        [Display(Name = "Paid")]
        Payed = 0,
        [Display(Name = "Unpaid")]
        NotPayed = 1
    }
}
