//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mongoose.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saved_Internship
    {
        public int Saved_InternshipId { get; set; }
        public int StudentId { get; set; }
        public int InternshipId { get; set; }
    
        public virtual Internship Internship { get; set; }
        public virtual Student Student { get; set; }
    }
}
