//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mongoose.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Student_Major
    {
        public int StudentMajorId { get; set; }
        [Display(Name = "Major")]
        public int MajorId { get; set; }
        [Display(Name = "Student")]
        public int StudentId { get; set; }
    
        public virtual Major Major { get; set; }
        public virtual Student Student { get; set; }
    }
}
