//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mongoose.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Student_Internship
    {
        public int StudentInternshipId { get; set; }
        [Display(Name = "Student ID")]
        
        public int StudentId { get; set; }
        [Display(Name = "Instructor ID")]
        public int InstructorId { get; set; }
        [Display(Name = "Internship ID")]
        public int InternshipId { get; set; }
        public string Midterm { get; set; }
        public string Final { get; set; }
        public string Comments { get; set; }
        [Display(Name = "Year")]
        [Required(ErrorMessage = "This field is required")]
        public int Term { get; set; }
        public corSemester Semester { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual Internship Internship { get; set; }
        public virtual Student Student { get; set; }
    }
}
